blog_app/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static
app_name = 'blog_app'

urlpatterns = [
    path('', views.PostListView.as_view(), name='PostListView'),
    path('post/<int:pk>', views.postDetailView.as_view(), name='PostDetailView'),
    path('add_post/',login_required(views.PostCreateView.as_view()), name='PostCreateView'),
    path('post/edit/<int:pk>', login_required(views.PostUpdateView.as_view(), login_url= reverse_lazy('members_app:login')), name='PostUpdateView'),
    path('post/<int:pk>/delete', login_required(views.PostDeleteView.as_view(), login_url= reverse_lazy('members_app:login')), name = 'PostDeleteView'),
    path('like/<int:pk>', views.like, name = 'like'),
    
    #category
    path('category', login_required(views.CategoryCreateView.as_view()), name = 'CategoryCreateView'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name = 'CategoryDetailView'),
    path('category/categories', views.CategoryListView.as_view(), name = 'CategoryListView'),
    path('category/<int:pk>/delete', views.CategoryDeleteView.as_view(), name = 'CategoryDeleteView'),
    path('category/<int:pk>/update', views.CategoryUpdateView.as_view(), name = 'CategoryUpdateView'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog_app.urls')),
    
    path('members/',include('members_app.urls')),
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime,date
from ckeditor.fields import RichTextField 
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)
    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name

    
    def get_absolute_url(self):
        return reverse('blog_app:CategoryListView')
    
class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null= True)
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name = 'posts')
    likes = models.ManyToManyField(User, related_name='blog_posts',blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    
    
    def number_of_likes(self):
        return self.likes.count()
    
    
    def __str__(self):
        return self.title + ' by ' + self.author.username
    
    def get_absolute_url(self):
        return reverse('blog_app:PostDetailView', kwargs={'pk': self.pk})

blog_app/forms.py
from django import forms 
from .models import *
from ckeditor.fields import RichTextField

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author','category','body','image')
        
        widgets = {
            'title': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'post title'}),
            'author': forms.TextInput(attrs= {'class': 'form-control', 'id':'author', 'value': '', 'type':'hidden'}),
            'category': forms.Select(attrs= {'class': 'form-control dropdown-toggle'}),
            'body': forms.Textarea(attrs= {'class': 'form-control', 'placeholder': 'post body'}),
        }
        
        
class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body')
        
        widgets = {
            'title': forms.TextInput(attrs= {'class': 'form-control'}),
            'body': forms.Textarea(attrs= {'class': 'form-control'}),
        }
        

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        
        widgets = {
            'name': forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Category Title'}),
        }
        

blog_app/views.py
from django.shortcuts import render,get_object_or_404
from .models import *

from .forms import *
from django.views.generic import TemplateView,CreateView,UpdateView,DeleteView,ListView,DetailView
from django.http import HttpResponseRedirect
# Create your views here.



class PostListView(ListView):
    model = Post
    template_name = "blog_app/index.html"
    cats = Category.objects.all()
    ordering = ['-post_date']
    
def like(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    
    else:
        post.likes.add(request.user)
    
    return HttpResponseRedirect(reverse('blog_app:PostDetailView', args=[str(pk)]))

    

class postDetailView(DetailView):
    model = Post
    template_name = "blog_app/article_details.html"
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        likes_connected = get_object_or_404(Post, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True
        data['number_of_likes'] = likes_connected.number_of_likes()
        data['post_is_liked'] = liked
        return data
    


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog_app/forms/add_post_form.html"


class PostUpdateView(UpdateView):
    model = Post
    form_class = EditPostForm
    template_name = "blog_app/forms/edit_post_form.html"


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog_app/confirmDeletion/post_confirm_delete.html'
    def get_success_url(self):
        return reverse('blog_app:PostListView')


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "blog_app/forms/add_category_form.html"
    

class CategoryListView(ListView):
    model = Category
    template_name = "blog_app/categories.html"
    

class CategoryDetailView(DetailView):
    model = Category
    template_name = "blog_app/category_details.html"


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'blog_app/confirmDeletion/category_confirm_delete.html'
    
    def get_success_url(self):
        return reverse('blog_app:CategoryListView')
    

class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "blog_app/forms/edit_post_form.html"

templates/blog_app/article_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{post.title}}
{% endblock title %}
    
{% block content %}
    <div class="container">
        <h1>{{post.title}}</h1>
        <small>by {{post.author.first_name}} 
            {{post.author.last_name}}-
            {{post.post_date}}


            {% if user.is_authenticated %}
                
                {% if user.id == post.author.id %}
                    -<a href="{%  url 'blog_app:PostUpdateView' pk=post.pk  %}">(Edit)</a>
                    -<a href="{% url 'blog_app:PostDeleteView' pk=post.pk %}">(Delete)</a>
                {% endif %}
            {% endif %}
            
        </small><br>
        <hr>
        <br>
        {% if post.image %}
            <img src="{{ post.image.url }}" width=500>
        {% else %}
            <p>no image</p>

        {% endif %}


        <br>
        {{post.body|safe}}
        
        
        <a href="{% url 'blog_app:PostListView' %}" class="btn btn-secondary">Go Back</a>
        <br></br>
        
        {% if user.is_authenticated %}
            <form action="{% url 'blog_app:like' post.pk %}" method="post">
                {% csrf_token %}
                
                {% if post_is_liked %}
                    <button class="btn btn-block btn-danger" value="{{post.id}}" name ="post_id"><i class="fa fa-thumbs-down"></i> </button>
                {% else %}
                    <button class="btn btn-block btn-primary" value="{{post.id}}" name ="post_id"><i class="fa fa-thumbs-up"></i> </button>
                {% endif %}
                    
                
            </form>
            {% else %}
            <a class="btn btn-outline-info" href="{% url 'members_app:login' %}?next={{request.path}}">Log in to like this article!</a><br>
        {% endif %}
        <strong class="text-secondary">{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>
    </div>
{% endblock %}

templates/blog_app/categories.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
  <h1>Categories List</h1>
  <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Category Title</th>
            
            
            {% if user.is_authenticated %}
              <th>Details</th>
              <th>Delete Category</th>
            {% endif %}
              
            

          </tr>
        </thead>
        {% for category in category_list %}
          <tbody>
            <tr>
              <td>{{ category.id }}</td>
              <td>{{ category.name }}</td>
            
              {% if user.is_authenticated %}
                <td>
                  <button class="btn btn-primary" onclick="window.location.href = '{% url 'blog_app:CategoryDetailView' pk=category.pk %}'">Category Details</button>
                </td>
                <td>
                  <button class="btn btn-danger" onclick="window.location.href = '{% url 'blog_app:CategoryDeleteView' pk=category.pk %}'">Delete Category</button>
                </td>
              {% endif %}
              
            </tr>
          </tbody>
        {% endfor %}
      </table>
    
  </div>
</div>
{% endblock content %}
  

templates/blog_app/category_details.html
{% extends 'base.html' %}

{% block title %}
    {{category.name}}
{% endblock title %}
    
{% block content %}
    <div class="container">
        <h1>{{category.name}}</h1>

            {% if user.is_authenticated %}
              -<a href="{%  url 'blog_app:CategoryUpdateView' pk=category.pk  %}">(Edit)</a>
              -<a href="{% url 'blog_app:CategoryDeleteView' pk=category.pk %}">(Delete)</a>
            {% endif %}
            
        </small><br>
        <hr>
        <br>
        <h2>Posts of the {{category.name}}</h2>

        <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Post Title</th>
                  <th>Author</th>
                  <th>Category</th>
                  <th>View Details</th>
                  
                  {% if user.is_authenticated %}
                    <th>Edit Post</th>
                    <th>Delete Post</th>
                  {% endif %}
                </tr>
              </thead>
            {% for post in category.posts.all %}
                <tbody>
                    <tr>
                    <td>{{ post.id }}</td>
                    <td>{{ post.title }}</td>
                    <td>{{ post.author }}</td>
                    <td>{{ post.category.name }}</td>
                     
                    <td>
                        <button class="btn btn-secondary" onclick="window.location.href = '{% url 'blog_app:PostDetailView' pk=post.pk %}'">View Post Details</button>
                    </td>
                    {% if user.is_authenticated %}
                        <td>
                        <button class="btn btn-primary" onclick="window.location.href = '{% url 'blog_app:PostUpdateView' pk=post.pk %}'">Edit Post</button>
                        </td>
                        <td>
                        <button class="btn btn-danger" onclick="window.location.href = '{% url 'blog_app:PostDeleteView' pk=post.pk %}'">Delete Post</button>
                        </td>
                    {% endif %}
                    
                    </tr>
                </tbody>
            {% endfor %}

            
        
        <br><br>
        <a href="{% url 'blog_app:CategoryListView' %}" class="btn btn-secondary">Go Back</a>
    </div>
{% endblock content%}

templates/blog_app/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
  <h1>Articles List</h1>
  <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Post Title</th>
            <th>Author</th>
            <th>Category</th>
            <th>View Details</th>
            
            {% if user.is_authenticated %}
              
                <th>Edit Post</th>
                <th>Delete Post</th>
            {% endif %}
              
            

          </tr>
        </thead>
        {% for post in post_list %}
          <tbody>
            <tr>
              <td>{{ post.id }}</td>
              <td>{{ post.title }}</td>
              <td>{{ post.author.username }}</td>
              <td>{{ post.category }}</td>

              <td>
                <button class="btn btn-secondary" onclick="window.location.href = '{% url 'blog_app:PostDetailView' pk=post.pk %}'">View Post Details</button>
              </td>
              {% if user.is_authenticated %}

                {% if user.id == post.author.id %}
                  <td>
                    <button class="btn btn-primary" onclick="window.location.href = '{% url 'blog_app:PostUpdateView' pk=post.pk %}'">Edit Post</button>
                  </td>
                  <td>
                    <button class="btn btn-danger" onclick="window.location.href = '{% url 'blog_app:PostDeleteView' pk=post.pk %}'">Delete Post</button>
                  </td>
                {% endif %}
                
              {% endif %}
              
            </tr>
          </tbody>
        {% endfor %}
      </table>
    
  </div>
  
    
</div>
{% endblock content %}
  