blog_app/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static
app_name = 'blog_app'

urlpatterns = [
    path('', views.PostListView.as_view(), name='PostListView'),
    path('post/<int:pk>', views.postDetailView.as_view(), name='PostDetailView'),
    path('add_post/',login_required(views.PostCreateView.as_view()), name='PostCreateView'),
    path('post/edit/<int:pk>', login_required(views.PostUpdateView.as_view(), login_url= reverse_lazy('members_app:login')), name='PostUpdateView'),
    path('post/<int:pk>/delete', login_required(views.PostDeleteView.as_view(), login_url= reverse_lazy('members_app:login')), name = 'PostDeleteView'),
    path('like/<int:pk>', views.like, name = 'like'),
    
    #category
    path('category', login_required(views.CategoryCreateView.as_view()), name = 'CategoryCreateView'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name = 'CategoryDetailView'),
    path('category/categories', views.CategoryListView.as_view(), name = 'CategoryListView'),
    path('category/<int:pk>/delete', views.CategoryDeleteView.as_view(), name = 'CategoryDeleteView'),
    path('category/<int:pk>/update', views.CategoryUpdateView.as_view(), name = 'CategoryUpdateView'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog_app.urls')),
    
    path('members/',include('members_app.urls')),
]

members_app/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'members_app'

urlpatterns = [
    path('UserRegisterView/', views.UserRegisterView.as_view(), name='UserRegisterView'),
    path('login/', auth_views.LoginView.as_view(template_name='members_app/forms/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('updateProfile/', views.UpdateProfileView.as_view(), name = 'UpdateProfileView'),
    path('password/', views.PasswordChangeView.as_view(), name = 'PasswordChangeView'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} posts {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog_app:PostListView' %}"
          >Posts</a
        >

        <a class="navbar-brand" href="{% url 'blog_app:CategoryListView' %}"
          >Categories</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'blog_app:PostCreateView' %}"
                >Add Post</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'members_app:logout' %}"
                >Logout</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'blog_app:CategoryCreateView' %}"
                >Add Category</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'members_app:UpdateProfileView' %}"
                >Edit Profile</a
              >
            </li>

            {% else %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'members_app:UserRegisterView' %}"
                >Register</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'members_app:login' %}"
                >Login</a
              >
            </li>

            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <br />
    {% block content %} {% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>